name: Cronjob
on: 
  schedule:
    - cron: '* * * * *'

jobs:
  cronjobname:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

# setup python
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Run python Script
      run: python hello1.py
