name: Send Mail
on: push

jobs:
  sendmail:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Testing"
     
    - name: Sending a mail
      if: ${{ always() }}
      uses: devellany/send-mailer@v1.0.2
      with:
        host: smtp.google.com
        # Optional port (defaults to 465)
        port: 465
        account: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        sender: devellany
        from: ${{secrets.MAIL_ADDRESS}}
        to: premnathm@dckap.com
        subject: mail title.
        body: your messages.
        # Optional content type (defaults to text/plain)
        contentType: text/plain
        # Optional attachment files (JSON type. require property 'path')
        attachments: '[{"path":"README.md"}]'
